version: "3.7"

services:
    db:
        container_name: '${SQL_CNTNR_NAME}'
        image: mysql:5.7
        ports:
            - "32001:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: database
            MYSQL_USER: user
            MYSQL_PASSWORD: password


    app:
        links:
            - "db"
        image: '${IMG_BUILDER}:${VERSION}'
        container_name: '${APP_CNTNR_NAME}'
        build: 
            context: ./src/
            dockerfile: Dockerfile
        
        volumes:
            - './src/:/app/src'
            - './data:/app/data'
            - './models:/app/models'
            - './config:/app/config'
            - './logs:/app/logs'
            - '/tmp/.X11-unix:/tmp/.X11-unix'
        environment:
            - DISPLAY=$DISPLAY

        # command: 'python3 src/gui.py --cfg config/config.yml'
        command: 'sh'


    webserver:
        image: '${WEB_IMG_BUILDER}:${VERSION}'
        container_name: '${WEBAPP_CNTNR_NAME}'
        build: 
            context: ./webapp/
            dockerfile: Dockerfile
        ports:
            - 8080:8080

      
        network_mode: host
        volumes:
            - './data/download:/app/data/download'
            - './models:/app/models'
            - './config:/app/config'
        command: ' python3 webapp.py '
        # command: 'sh'

