name: hais-runner
on: [push]

env:
  PYTHON_VERSION: "3.8"

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{env.PYTHON_VERSION}}
        uses: actions/setup-python@v3
        with:
          python-version: ${{env.PYTHON_VERSION}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Link with flake8 [debugging python syntax]
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test the code using Pytest
        run: |
          pytest

  test_modules:
    needs: build_test
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - name: Setup the environemnt (pip)
        run: |
          # install packages
          pip install -r requirements.txt

      - name: Run the test pipeline
        run: |
          # run the code tests
          src/test/test_codes.sh >> results.md

      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Post reports as comments in GitHub PRs
          ls -a
          cat results.md >> report.md
          cml comment create report.md
